# Generated by Django 4.2.7 on 2023-11-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='style',
            name='season',
            field=models.CharField(max_length=16),
        ),
    ]
