# Generated by Django 4.1.5 on 2023-11-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outfits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="style", old_name="seson", new_name="season",
        ),
    ]
