# Generated by Django 4.1.5 on 2023-11-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("brand", models.CharField(max_length=64)),
                ("origin_price", models.IntegerField()),
                ("discounted_price", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={"db_table": "tb_goods",},
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=16)),
                ("views", models.IntegerField(default=0)),
                ("seson", models.CharField(max_length=8)),
                ("URL", models.TextField(null=True)),
                ("tag", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "tb_style",},
        ),
        migrations.CreateModel(
            name="StyleGoods",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outfits.goods"
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outfits.style"
                    ),
                ),
            ],
            options={"db_table": "tb_style_goods",},
        ),
    ]
